export enum Routes {
  Home = "Inicio",
  Chat = "Chat",
  Login = "Iniciar Sesión",
  Signup = "Registrarse",
  Logout = "Cerrar Sesión",
  Licence = "Mi carnet",
  LoginFingerprint = "Iniciar Sesión con Huella",
  LoginFace = "Iniciar Sesión con Reconocimiento Facial",
  Loans = "Préstamos",
  RegisterFace = "Registrar Rostro",
  MyLoans = "Préstamos solicitados",
  Carnet = "Mi Carnet",
  BookList = "Solicitar préstamo",
  ShowLoans = "Mis Préstamos",
  UserConfiguration = "Configuración",
}
