export enum Routes {
  Home = "Inicio",
  Chat = "Chat",
  Login = "Iniciar Sesión",
  Signup = "Registrarse",
  Logout = "Cerrar Sesión",
  Licence = "Mi carnet",
  LoginFingerprint = "Iniciar Sesión con Huella",
  LoginFace = "Iniciar Sesión con Reconocimiento Facial",
  Loans = "Préstamos",
  RegisterFace = "Registrar Rostro",
  MyLoans = "Mis préstamos",
  Carnet = "Mi Carnet",
  RequestLoans = "Solicitar préstamo",
  UserConfiguration = "Configuración",
  TempQr = "Escanear QR",
  ViewQr = "Ver QR",
  CreateDeleteLibrarian = "Alta de bibliotecarios",
  RUDUser = "Actualización de usuario",
  LibrarianLoans = "Prestamos solicitados por usuarios",
  LoanCreation = "Alta de prestamo"
}
