name: Python Tests

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**/*.py'
  pull_request:
    paths:
      - 'Backend/**/*.py'


jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.12"

    steps:
      - name: Checks out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f Backend/dev-requirements.txt ]; then pip install -r Backend/dev-requirements.txt; fi
          if [ -f Backend/requirements.txt ]; then pip install -r Backend/requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest Backend/test/
